stack-of-tasks/eigenpy

README.md
In my case, I "only" did a `git clone <git_url>`. Afterwards it took me a few minutes to figure out how to get the repo to compile.
Propose adding a comment about this in the `README.md`.
=> Need to initialize submodules before compiling.

CMakeLists.txt
=> Fix boost python detection problem to allow multiple python interpreters

CMakeLists.txt, COPYING.LESSER, include/eigenpy/angle-axis.hpp, include/eigenpy/details.hpp, include/eigenpy/eigenpy.hpp, include/eigenpy/exception.hpp, include/eigenpy/fwd.hpp, include/eigenpy/geometry-conversion.hpp, include/eigenpy/geometry.hpp, include/eigenpy/map.hpp, include/eigenpy/memory.hpp, include/eigenpy/quaternion.hpp, include/eigenpy/ref.hpp, include/eigenpy/registration.hpp, include/eigenpy/stride.hpp, python/CMakeLists.txt, python/main.cpp, src/angle-axis.cpp, src/eigenpy.cpp, src/exception.cpp, src/geometry-conversion.cpp, src/quaternion.cpp, unittest/CMakeLists.txt, unittest/geometry.cpp, unittest/matrix.cpp, unittest/ref.cpp
=> Change license to be BSD-2-Clause

include/eigenpy/details.hpp
Related to #63.
cc @rhaschke seems to solve your issue.
=> core: fix dimensions of vecrtor for Array conversion

.travis.yml, CMakeLists.txt
Do not compile with catkin.
Related to #69
=> Improve compatibility with travis

include/eigenpy/details.hpp
It removes debugging messages.
=> Removed debugging messages

include/eigenpy/details.hpp, src/eigenpy.cpp, unittest/python/test_geometry.py, unittest/python/test_switch.py
=> Expose getNumpyType

.gitlab-ci.yml
https://gepgitlab.laas.fr/gsaurel/eigenpy/pipelines/7470
=> [CI] use memmos instead of eur0c

include/eigenpy/details.hpp, include/eigenpy/map.hpp, unittest/matrix.cpp, unittest/python/test_matrix.py
=> Add test for matrix 1x1

include/eigenpy/angle-axis.hpp, include/eigenpy/decompositions/EigenSolver.hpp, include/eigenpy/decompositions/LDLT.hpp, include/eigenpy/decompositions/LLT.hpp, include/eigenpy/decompositions/SelfAdjointEigenSolver.hpp, include/eigenpy/eigen-from-python.hpp, include/eigenpy/quaternion.hpp
=> Fix destruction of objects 

include/eigenpy/ufunc.hpp
=> Fix compilation issues with NumPy 1.19

include/eigenpy/quaternion.hpp, unittest/python/test_geometry.py
=> Fix init call order

include/eigenpy/quaternion.hpp
=> Fix quaternion static Identity constructor 

include/eigenpy/quaternion.hpp
#231 should be working fine.
The issue is really coming from Eigen and Boost.Python. Not from EigenPy. I will try to provide a cleaner fix soon.
=> Additional fix

unittest/user_type.cpp
=> Comment useless print

include/eigenpy/numpy-map.hpp, unittest/matrix.cpp, unittest/python/test_matrix.py
=> Fix RowMajor issues

include/eigenpy/quaternion.hpp
=> Fix Quaternion constructor

include/eigenpy/quaternion.hpp, src/quaternion.cpp
=> Fix memory issue with Quaternion::normalized

.git-blame-ignore-revs, .pre-commit-config.yaml, CMakeLists.txt, python/CMakeLists.txt, unittest/CMakeLists.txt
=> pre-commit / cmake-format

.github/workflows/macos-linux-conda.yml, .github/workflows/windows-conda.yml, unittest/packaging/cmake/CMakeLists.txt
Same idea as #296, but for projects that don't have the jrl-cmakemodules.
I think the CI will fail here, let's check this :)
=> ci: test packaging

CMakeLists.txt
=> CMake: typo

CMakeLists.txt, include/eigenpy/memory.hpp
=> FIx issue related to Python 3.10

CMakeLists.txt
=> define HAVE_SNPRINTF for windows, fix #309

.pre-commit-config.yaml, README.md, benchmarks/bench-switch.py, python/eigenpy/__init__.py, setup.cfg, unittest/eigen_ref.cpp, unittest/python/test_LLT.py, unittest/python/test_complex.py, unittest/python/test_dimensions.py, unittest/python/test_eigen_ref.py, unittest/python/test_geometry.py, unittest/python/test_return_by_ref.py, unittest/python/test_self_adjoint_eigen_solver.py, unittest/python/test_user_type.py
Should fix the failing format job on gepgitlab
=> Fix flake8 errors

python/CMakeLists.txt
ref. https://github.com/stack-of-tasks/eigenpy/issues/353 
ref. https://github.com/jrl-umi3218/jrl-cmakemodules/pull/588
=> fix INSTALL_RPATH on ROS & OSX

.github/workflows/check-changelog.md
Check if a changelog if updated before allowing a merge request
=> ci: add ci step to check changelog update before merging in master

.github/workflows/jrl-cmakemodules.yml, .github/workflows/ros_ci.yml
Hi,
This add a regression test for #405. For now, it shouldn't pass.
=> CMake: check version is not 0.0

.github/workflows/conda/environment_macos_linux.yml, .github/workflows/conda/environment_windows.yml, .github/workflows/macos-linux-conda.yml, .github/workflows/windows-conda.yml
- Use the right key to update ccache cache at each run
- Add ccache to windows
- Modernize the ci steps
- Use conda compiler
=> Fix ccache

.github/workflows/conda/environment_macos_linux.yml, .github/workflows/conda/environment_windows.yml, .github/workflows/jrl-cmakemodules.yml, .github/workflows/linux.yml, .github/workflows/macos-linux-conda.yml, .github/workflows/reloc.yml, CHANGELOG.md, CMakeLists.txt, include/eigenpy/details.hpp, include/eigenpy/eigen-from-python.hpp, include/eigenpy/eigen-to-python.hpp, include/eigenpy/eigenpy.hpp, include/eigenpy/fwd.hpp, include/eigenpy/numpy-type.hpp, include/eigenpy/register.hpp, include/eigenpy/scalar-conversion.hpp, include/eigenpy/scipy-allocator.hpp, include/eigenpy/scipy-type.hpp, include/eigenpy/sparse/eigen-from-python.hpp, src/matrix-long.cpp, src/register.cpp, src/scipy-type.cpp, unittest/CMakeLists.txt, unittest/python/test_sparse_matrix.py, unittest/python/test_tensor.py, unittest/sparse_matrix.cpp, unittest/tensor.cpp
Still missing the support for `Eigen::Ref<Eigen::SparseMatrix<D>>`
=> Add support for Eigen::SparseMatrix

README.md
This PR is a suggestion to clarify in the readme that SVD and QR are possible but not implemented at present. It does so by adding a Contributing section at the bottom.
Closes https://github.com/stack-of-tasks/eigenpy/issues/460
=> Add Contributing section to the readme

LICENSE
=> Sync license
