src/details.hpp

Fix bug concerning the pragma pedantic. Should compile with gcc 4.8.

[Bug fix] Remove the pragma line leading to error with gcc 4.8

---

.gitignore
CMakeLists.txt
src/details.cpp
src/details.hpp
src/eigenpy.cpp
src/exception.cpp
src/fwd.hpp
src/quaternion.hpp
unittest/geometry.cpp

This PR aims at enabling the alignment between eigen and numpy objects (EIGEN_NUMPY_ALIGNED must be set to ON in Cmake).

Enable alignment between Eigen matrix and Numpy matrix

---

src/fwd.hpp

* It allows creating unaligned equivalent of Eigen matrix using a
different scalar type. This can be useful when matrix types use
single precision floats, whereas Numpy matrix types use double
precision floats by default.
* Default template argument value is Matrix D scalar type to preserve
backward-compatibility.

Add Scalar template argument to UnalignedEquivalent struct.

---

README.md
include/eigenpy/details.hpp

Fix wrong message error

---

include/eigenpy/details.hpp

Related to #35 
I don't know exactly why this works (and whether this works for everyone).

Fix SEGV with Python 3.

---

include/eigenpy/angle-axis.hpp
include/eigenpy/quaternion.hpp
include/eigenpy/registration.hpp

Related to https://github.com/stack-of-tasks/pinocchio/pull/817

Registration

---

.travis.yml
include/eigenpy/details.hpp

Add warnings when implicitly using numpy.matrix.

---

package.xml

This PR fixes the unstable build warnings we are getting via email every time a PR is merged to master. It also updates the version number to the yet-to-be-released 1.6.2 which I suggest to tag and release once this PR is merged.
After this PR, I will make a new ROS buildfarm release which also changes from the previous catkinized version to regular third-party library. As part of this, I will update MoveIt to comply with the pkg-config search (as I believe #98 may take longer).

Update package.xml to fix unstable build warnings

---

eigenpyConfig.cmake

As cmake expects absolute library paths, while pkgconfig provides lib names only (together with
LIBRARY_DIRS), one needs to transform names to full library paths.
This fixes 7854c0f / #101. Without this fix, the MoveIt catkin build still fails with:
```
Errors     << moveit_ros_planning_interface:make /vol/sandbox/ros/logs/moveit_ros_planning_interface/build.make.000.log
/usr/bin/ld: cannot find -leigenpy
collect2: error: ld returned 1 exit status
```

eigenpyConfig.cmake: find absolute library paths for all required libs

---

include/eigenpy/details.hpp
unittest/python/test_geometry.py
unittest/python/test_matrix.py

Switch to np.array type by default

---

.travis.yml
CMakeLists.txt
include/eigenpy/details.hpp
include/eigenpy/eigenpy.hpp
src/eigenpy.cpp
src/matrix-complex-double.cpp
src/matrix-complex-float.cpp
src/matrix-complex-long-double.cpp
src/matrix-double.cpp
src/matrix-float.cpp
src/matrix-int.cpp
src/matrix-long-double.cpp
src/matrix-long.cpp
unittest/python/test_matrix.py

A matrix with a single column should be considered as classic np.array

core: revert previous settings

---

include/eigenpy/details.hpp
include/eigenpy/details/rvalue_from_python_data.hpp
include/eigenpy/utils/is-approx.hpp
python/main.cpp

@duburcqa Could try this potential fix?

Template specialization for sized Eigen::{MatrixBase,EigenBase}

---

include/eigenpy/numpy-allocator.hpp
include/eigenpy/numpy.hpp
src/numpy.cpp

which is not able to retrieve EIGENPY_ARRAY_API when compiling other module because the symbol is not exported

core: patch Win32

---

.github/workflows/build.yml
ci/environment.yml

I am trying to synthesize the build process we used in [`eigenpy-feedstock`](https://github.com/conda-forge/eigenpy-feedstock), but do it in GitHub workflow.
Hope that can catch Windows build issues per check-in.

Adding GitHub workflow as Windows CI

---

.gitlab-ci.yml

Hi,
This PR updates the gitlab CI configuration from the generated configuration at https://rainboard.laas.fr/project/eigenpy/.gitlab-ci.yml (which is now accessible from the LAAS, or with LAAS credentials, or with a custom account)
This:
- add the doc-coverage target, to save the generated documentation an code-coverage results
- add the format target, to check the code formatting (allow_failure is activated here for now), ref https://github.com/gepetto/linters
- set 18.04 as the main platform (for now, this affects only format & doc-coverage target)
- allow automatic retries in case of runner failures
- drop 14.04 checks
Before: https://gepgitlab.laas.fr/stack-of-tasks/eigenpy/pipelines/8522
After: https://gepgitlab.laas.fr/gsaurel/eigenpy/pipelines/8523

[CI] update gitlab CI

---

include/eigenpy/numpy-allocator.hpp

Remove a few conversion warnings.
Eigenpy doesn't issue any compilation warnings now.

Remove silly warnings

---

include/eigenpy/decompositions/LLT.hpp

Return type of LLT::rankUpdate was changed from LLT (value) to LLT& (reference) on Eigen master branch

Fix LLT with current Eigen master branch

---

package.xml

This adds compatibility with Ubuntu 20.04 and distributions that default to Python 3.
I've tested this with a CI based on 20.04.

package.xml: Prepare for Ubuntu 20.04 / Python3

---

README.md
package.xml

@wxmerkt Just before the new release

Sync submodule CMake

---

package.xml

Required for packaging according to REP-136

package.xml: Add exec_depend on catkin or ament_cmake

---

include/eigenpy/eigen-allocator.hpp
include/eigenpy/fwd.hpp
include/eigenpy/numpy-map.hpp
include/eigenpy/user-type.hpp
unittest/matrix.cpp

Fix bug for non square matrix

---

include/eigenpy/details.hpp
include/eigenpy/eigen-from-python.hpp
include/eigenpy/eigen-to-python.hpp
include/eigenpy/numpy-allocator.hpp
unittest/eigen_ref.cpp
unittest/matrix.cpp
unittest/python/test_eigen_ref.py
unittest/python/test_matrix.py

Add support for exporting Eigen::Ref to Python

---

include/eigenpy/quaternion.hpp

Fix constructors for Quaternion

---

CMakeLists.txt

Setting INSTALL_DOCUMENTATION OFF wasn't respected as it was overridden
in post-project.cmake which gets called upon setting PROJECT(). Moving
the settings prior to the include of base.cmake, it works as intended.

Move block to set OPTIONS before including base.cmake

---

include/eigenpy/quaternion.hpp
unittest/matrix.cpp
unittest/python/test_geometry.py

Fix quaternion initialisation segfault under -march=native

---

include/eigenpy/angle-axis.hpp
include/eigenpy/eigen-from-python.hpp
include/eigenpy/eigen-to-python.hpp
include/eigenpy/numpy.hpp
include/eigenpy/quaternion.hpp
python/main.cpp

This PR allows exposing the name of the objects in the Boost.Python doc.

Export name types

---

unittest/eigen_ref.cpp
unittest/python/test_eigen_ref.py

This commit adds a test where the user exposes a struct with an `Eigen::Ref` data member and shows how to expose it using the right `boost::python::return_value_policy`.

test/eigen_ref: test using Eigen::Ref as data member

---

include/eigenpy/numpy-allocator.hpp
unittest/python/test_eigen_ref.py

This PR:
* adds tests where user takes (1,n) or (n,1) blocks of matrices as `Eigen::Ref` and returns them to NumPy
* fixes the corner case where (n,1) was taken
* builds on fix for `RowMajor` in 471b8d65bff9240239e6d490100d97074a429952

Fix for Refs to dynamic (1, N) blocks

---

CMakeLists.txt
colcon.pkg

Required in order for PYTHONPATH to be set up correctly after sourcing a workspace built with colcon

ROS2/Colcon integration for AMENT_PREFIX_PATH and PYTHONPATH

---

CMakeLists.txt

Depends on https://github.com/jrl-umi3218/jrl-cmakemodules/pull/523
Alternative for #294

Fix python numpy linking error

---

.github/workflows/ros_ci.yml

Our current CI configuration only ran prerelease tests for ROS2. We recently had a CMake breakage for Python2
@nim65s Can you please look into why the new CMake does not correctly configure for Python2 on 18.04?
Cf.
https://github.com/ros/rosdistro/pull/34135#issuecomment-1221034543
https://github.com/stack-of-tasks/eigenpy-ros-release/issues/4

[CI] Always run PRERELEASE tests

---

unittest/python/test_LDLT.py
unittest/python/test_MINRES.py
unittest/python/test_eigen_solver.py

~~Do not merge as it currently points to a fork of jrl-cmakemodules.~~
PR to verify with the EigenPy builds that the updated `FindBoost.cmake` works on all target platforms

Test https://github.com/jrl-umi3218/jrl-cmakemodules/pull/547

---

include/eigenpy/numpy-map.hpp
unittest/python/test_matrix.py

I'm currently running into the following issue on master (v2.7.14), noted [here](https://aur.archlinux.org/packages/eigenpy#comment-881903).
```
❯ ARGS="--output-on-failure" make test 
Running tests...
/usr/bin/ctest --force-new-ctest-process --output-on-failure
Test project /home/anthony/code/aur-testing/eigenpy/build
Start  1: matrix
1/21 Test  #1: matrix ...........................   Passed    0.17 sec
Start  2: geometry
2/21 Test  #2: geometry .........................   Passed    0.16 sec
Start  3: complex
3/21 Test  #3: complex ..........................   Passed    0.16 sec
Start  4: return_by_ref
4/21 Test  #4: return_by_ref ....................   Passed    0.17 sec
Start  5: include
5/21 Test  #5: include ..........................   Passed    0.11 sec
Start  6: eigen_ref
6/21 …
```

Modify stride assertion in `numpy-map.hpp` to be valid for empty vector

---

unittest/CMakeLists.txt
unittest/python/test_user_struct.py
unittest/user_struct.cpp

This PR adds a test wherein a user-defined struct containing fixed-size Eigen members are exposed with getters and setters (similarly to `pinocchio.GeometryObject`'s `meshColor` member).
With the `-mavx2` compile flag, the test succeeds with Boost>=1.77, but fails triggering a segfault on 1.76 and 1.74 (which is required by conda ROS noetic) when assigning to the `Eigen::Vector4d` type member a follows:
```python
ms.y = y
```
However, a slicing-assignment `ms.y[:] = y` does not trigger a segfault.
Assigning to the Vector3d member does not trigger a segfault.  
Without the AVX flag, the test does not fail (so the CI will pass).
Compiler: clang++ 15
Environment: conda environment

Tests: add user-struct test

---

python/CMakeLists.txt

This PR:
* updates the cmake submodule
* uses the new feature where we can make the Python stubs depend on the Python bindings target

CMake: have python stubs target depend on pywrap target

---

CMakeLists.txt
include/eigenpy/optional.hpp
src/eigenpy.cpp
src/optional.cpp
unittest/bind_optional.cpp.in

This PR:
+ adds src/optional.cpp to expose none types
+ this allows to have None as a default arg value for functions (also, shows up in function signatures when stubs are enabled)
+ also allows to have none_t return/argument type

WIP: Expose boost::none_t type (and std::nullopt_t when available)

---

CMakeLists.txt

ref. https://github.com/jrl-umi3218/jrl-cmakemodules/issues/338 and fix deprecation warning about CMake 3.5 from CMake 3.27

CMake: require >= 3.10

---

include/eigenpy/registration_class.hpp
include/eigenpy/std-vector.hpp
unittest/std_vector.cpp

Avoid overload issue between
```cpp 
static void expose(const std::string &class_name, const std::string &doc_string);
```
and
```cpp
static void expose(const std::string &class_name, const Visitor &visitor);
```

core: fix StdVectorPythonVisitor::expose API

---

CHANGELOG.md
CMakeLists.txt
include/eigenpy/std-array.hpp
include/eigenpy/std-vector.hpp
unittest/CMakeLists.txt
unittest/python/test_std_array.py
unittest/std_array.cpp

**Remarks**
Slices (i.e. using `object[a:b]` in Python on a subscriptable object) of `std::array<Eigen::Matrix, K>` types do not work. They do work for other types - this comes from exposing the Eigen std::array types with `eigenpy::details::overload_base_item_for...` which redefines `::base_get_item` for the underlying indexing_suite visitor that is used.
I think they might not work for slices of `std::vector<Eigen::Matrix>` types either, no @jorisv ?
**Meta**
Resolves #411

Expose std::array types

---

.clang-format
.github/workflows/jrl-cmakemodules.yml
.github/workflows/linux.yml
.github/workflows/macos-linux-conda.yml
.github/workflows/reloc.yml
.github/workflows/ros_ci.yml
.github/workflows/windows-conda.yml
CHANGELOG.md
include/eigenpy/boost-variant.hpp
unittest/CMakeLists.txt
unittest/boost_variant.cpp
unittest/python/test_boost_variant.py

- Add `BoostVariantConverter` to register a `boost::variant` conversion to an alternatives and alternatives conversion to `boost::variant`.
- Add `ReturnInternalBoostVariant` to return an alternative reference
Also:
- Cancel CI workflow when a new commit is pushed

Add `boost::variant` support

---

CHANGELOG.md
CMakeLists.txt

Hi,
This fix exported CMake interface when CMAKE_INSTALL_INCLUDEDIR is not strictly include, and allow use of jrl-cmakemodule from an installed version

CMake details

---

CHANGELOG.md
include/eigenpy/numpy-allocator.hpp
include/eigenpy/numpy.hpp
include/eigenpy/user-type.hpp
src/numpy.cpp
src/register.cpp

Fixes https://github.com/stack-of-tasks/eigenpy/issues/447
It requires a follow-up PR in Boost::Python itself [here](https://github.com/boostorg/python/pull/432), but it does not prevent from merging this PR.

Add support of numpy 2.0.0b1

---

.github/workflows/macos-linux-conda.yml
.github/workflows/windows-conda.yml
CHANGELOG.md
include/eigenpy/eigen-from-python.hpp
include/eigenpy/eigen-to-python.hpp
include/eigenpy/fwd.hpp
include/eigenpy/register.hpp

On Windows EigenToPy/EigenFromPy are not defined (only specialized) to avoid a CL compiler issue.
If we make the following declaration:
```cpp
template <typename MatType,
typename Scalar =
typename boost::remove_reference<MatType>::type::Scalar>
struct EigenToPy;
```
CL complain that MatType is an undeclared identifier.
To avoid that, a first hack was to not define but only specialize EigenToPy (same for EigenFromPy) on Windows:
```cpp
template <typename EigenType>
struct EigenToPy<EigenType,
typename boost::remove_reference<EigenType>::type::Scalar>
: eigen_to_py_impl<EigenType> {
};
```
Unfortunately, this hack prevent to specialize EigenToPy for custom scalar type with CL.
This PR revert this hack and fix the first issue by moving the default Scalar definition in the EigenToPy …

Fix EigenToPy/EigenFromPy on Windows

---

CHANGELOG.md
include/eigenpy/registration.hpp
unittest/CMakeLists.txt
unittest/multiple_registration.cpp
unittest/python/test_multiple_registration.py

+ added a unit test where I expose the same class multiple times with the `register_symbolic_link_to_registered_type()` safeguard, it currently produces a wonderful 36 errors :D
+ add a missing incref in `register_symbolic_link_to_registered_type()` (thanks @jcarpent)
Here's the valgrind report without the fix:
[report.log](https://github.com/stack-of-tasks/eigenpy/files/15406791/report.log)

Add unit test multiple_registration, fix register_symbolic_link_to_registered_type() for multiple successive registrations

---

.github/workflows/ros_ci.yml
package.xml

Requires re-enabling the workflow. Should fix the broken buildfarm builds.

Fix ROS CI & compilation

---

include/eigenpy/deprecation-policy.hpp
unittest/bind_virtual_factory.cpp

I'm having issues with the new pre-commit config (it fails on MacOS Python2 venv config - on Linux) so formatting may not be applied yet. Hoping for pre-commit CI to correct me :-)

Fix warnings to address unstable build on buildfarm

---

CHANGELOG.md
include/eigenpy/std-vector.hpp

This PR adds the `std::vector` allocator type as a template parameter for the `exposeStdVectorEigenSpecificType()` convenience function.
This would be useful in C++17 codebases wherein `Eigen::aligned_allocator<T>` is no longer useful (as outlined [in the executive summary here](https://www.eigen.tuxfamily.org/dox-devel/group__TopicStlContainers.html)) and developers would want to stay with the default allocator.

[std-vector.hpp] make std::vector allocator type a template parameter for exposeStdVectorEigenSpecificType

---

CHANGELOG.md
include/eigenpy/std-map.hpp
unittest/CMakeLists.txt
unittest/python/test_std_map.py
unittest/std_map.cpp

There is no map converter in eigenpy yet, so I copied the snippet of code for bp::dict to std::map conversion from Crocoddyl and added it to this PR.

Add bp::dist to std::map converter + unittest

---

CHANGELOG.md
README.md
include/eigenpy/std-map.hpp
unittest/python/test_std_map.py
unittest/std_map.cpp

+ test boost::unordered_map
+ pull StdMapPythonVisitor out of eigenpy::python namespace (shouldn't exist, add using-decl for backwards compatibility)

[std-map] add more general visitor for map types, fix non-default-constructible types

---

CHANGELOG.md
CMakeLists.txt
include/eigenpy/map.hpp
include/eigenpy/std-map.hpp
include/eigenpy/std-vector.hpp
include/eigenpy/utils/empty-visitor.hpp
unittest/python/test_std_map.py
unittest/std_map.cpp

Also: 
- split GenericMapPythonVisitor into its own file `eigenpy/map.hpp`
- move `EmptyPythonVisitor` to its own header file `eigenpy/utils/empty-visitor`
- rename `overload_base_get_item_for_std_map` to drop the `std` mention, move out of `eigenpy::details` namespace
Resolves #506

Map enhancements: add visitor arg to ::expose() with overloads, rename `overload_base_get_item_for_std_map`

---

CHANGELOG.md
include/eigenpy/ufunc.hpp
include/eigenpy/user-type.hpp
src/register.cpp
unittest/python/test_user_type.py
unittest/user_type.cpp

Fix common issues in custom types

---

CHANGELOG.md
include/eigenpy/sparse/eigen-from-python.hpp
unittest/python/decompositions/sparse/test_SimplicialLLT.py

Fix issue for sparse matrix conversions
